apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: sharathchandranp/technogetic-auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: sharathchandranp/technogetic-tasks
          context: tasks
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        # - image: sharathchandranp/technogetic-client
        #   context: client
        #   docker:
        #       dockerfile: Dockerfile
        #   sync:
        #       manual:
        #           - src: '**/*{.js, .css}'
        #             dest: .
