apiVersion: apps/v1
kind: Deployment
metadata:
    name: tasks-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tasks
    template:
        metadata:
            labels:
                app: tasks
        spec:
            containers:
                - name: tasks
                  image: sharathchandranp/technogetic-tasks
                  env:
                      - name: MONGO_URI
                        valueFrom:
                            secretKeyRef:
                                name: mongo-secret
                                key: MONGO_SECRET
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
    name: tasks-srv
spec:
    selector:
        app: tasks
    ports:
        - name: tasks
          protocol: TCP
          port: 3000
          targetPort: 3000
